# Generated by Django 3.2.7 on 2021-11-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artsupply',
            name='media',
            field=models.CharField(choices=[('CH', 'Charcoal'), ('CP', 'Colored Pencil'), ('IA', 'Ink: Alcohol-based'), ('II', 'Ink: India'), ('IW', 'Ink: Water-based'), ('MA', 'Marker: Alcohol-based'), ('MW', 'Marker: Water-based'), ('PA', 'Paint: Acrylic'), ('PG', 'Paint: Gouache'), ('PO', 'Paint: Oil'), ('PW', 'Paint: Watercolor'), ('PH', 'Pastel: Hard'), ('OP', 'Pastel: Oil'), ('PP', 'Pastel: Pan'), ('PS', 'Pastel: Soft '), ('PB', 'Pen: Brush nib'), ('PL', 'Pen: Fineliner'), ('PF', 'Pen: Fountain')], default='CH', max_length=2),
        ),
    ]
