# Generated by Django 3.2.7 on 2021-11-25 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_artsupply_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artsupply',
            old_name='media',
            new_name='medium',
        ),
    ]
