# Generated by Django 3.2.7 on 2021-11-27 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='artsupply',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.artsupply'),
        ),
    ]
