# Generated by Django 3.2.7 on 2021-11-28 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_photo_artsupply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='artsupply',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.artsupply'),
        ),
    ]
