# Generated by Django 3.2.7 on 2021-11-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_artsupply_familiarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artsupply',
            name='favorite',
            field=models.BooleanField(verbose_name="Check this box if you'll use it again"),
        ),
    ]
