# Generated by Django 3.2.7 on 2021-11-29 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_photo_artsupply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='artsupply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main_app.artsupply'),
        ),
    ]
