# Generated by Django 3.2.7 on 2021-11-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_photo_artsupply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artsupply',
            name='medium',
            field=models.CharField(choices=[('CH', 'Charcoal'), ('CP', 'Colored Pencil'), ('IA', 'Alcohol Ink'), ('II', 'India Ink'), ('IW', 'Water-based Ink'), ('GR', 'Graphite'), ('MA', 'Alcohol Marker'), ('MW', 'Water-based Marker'), ('PA', 'Acrylic Paint'), ('PG', 'Gouache Paint'), ('PO', 'Oil Paint'), ('PW', 'Watercolor Paint'), ('PH', 'Hard Pastel'), ('OP', 'Oil Pastel'), ('PP', 'Pan Pastel'), ('PS', 'Soft Pastel'), ('BP', 'Ballpoint Pen'), ('PB', 'Brush Pen'), ('GE', 'Gel Pen'), ('PL', 'Fineliner Pen'), ('PF', 'Fountain Pen'), ('PE', 'Paint Pen')], default='CH', max_length=2),
        ),
    ]
